name: Run Cypress Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
      - name: Run Yarn 
        run: yarn 
      - name: install node modules
        uses: tecolicom/actions-install-node-modules@v1.2
      - name: Build Yarn 
        run: yarn build
