name: Run Cypress Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  NAPI_CLI_VERSION: 2.13.3
  TURBO_VERSION: 1.6.3
  PNPM_VERSION: 7.24.3
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
      - run: npm i -g "pnpm@${PNPM_VERSION}" "@napi-rs/cli@${NAPI_CLI_VERSION}" "turbo@${TURBO_VERSION}"
        name: install npm packages
