name: Automated Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with: 
        node-version: 18.x
        cache-dependency-path: package-lock.json
    - name: Setup pnpm
      run: npm install -g pnpm
    - uses: actions/cache@v3.2.6
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: pnpm install
      run: pnpm install --no-frozen-lockfile
    - name: Install turbo
      run: npm i turbo
    - name: pnpm build
      run: pnpm build
    - name: pnpm start
      run: pnpm start &
    - name: pnpm test
      run: pnpm test
