name: Run Cypress Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '18.x'
          cache: 'yarn'
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
      - name: GitHub Action for Yarn - install
        uses: Borales/actions-yarn@v4.2.0
        with:
            cmd: install
      - name: GitHub Action for Yarn - build
        uses: Borales/actions-yarn@v4.2.0
        with:
            cmd: build
